### ISSUE TITLE
hi, error?

### ISSUE THREAD

**Issue by HadXu** [jonathanking/protein-transformer#8]
when I run your code and use `casp12_200123_100.pt`   occur follow error

`Traceback (most recent call last):
  File "train.py", line 624, in <module>
    main()
  File "train.py", line 559, in main
    angle_means = data["settings"]["angle_means"]
KeyError: 'angle_means'`

**Comment by jonathanking** [comment]
Hello, thanks for reaching out! 

That error was because I have updated the format of the dataset. Please download the updated version [here](https://pitt.box.com/s/gcaxsjbdhjp4zsyjzqbvum8795w8vay5). I have also updated the link in the README.  

One other thing you should note is that you should also modify the `wandb` project details in `train.py` so that they point to your account, not mine!
